### ISSUE TITLE
Problem to compile with Pelles C

### ISSUE THREAD

**Issue by milen-prg** [jlelong/pnl#6]
I use Pelles C compiler (Windows 10 Pro 64 bit) and try to compile simple example:

`#include <stdio.h>
#include <pnl/pnl_complex.h>

int main(int argc, char *argv[])
{
    dcomplex z = Complex(-1, 0);
    printf("%f\n",  Csqrt(z).r);
    return 0;
}
`

The compilation and linking is successful. Program exe starts with or without dlls. But crashes immediately at function Complex().

The IDE gives this messages:

C:\Users\mlap\Documents\pellesCmath1\pellesCmath1.exe.
POLINK: warning: Section '.idata$7' is not supported; image will probably not run.
POLINK: warning: Section '.idata$7' is missing contents flag; assuming DATA.
POLINK: warning: Section '.idata$5' is missing contents flag; assuming DATA.
POLINK: warning: Realigned section '.idata$5' in object 'libpnl.lib(0              1673985086  501   20    644     261       `
d†)' (from 4 to 8 byte(s)).
POLINK: warning: Section '.idata$4' is missing contents flag; assuming DATA.
POLINK: warning: Realigned section '.idata$4' in object 'libpnl.lib(0              1673985086  501   20    644     261       `
d†)' (from 4 to 8 byte(s)).
POLINK: warning: Section '.idata$6' is missing contents flag; assuming DATA.
POLINK: warning: Section '.idata$7' is missing contents flag; assuming DATA.
POLINK: warning: Section '.idata$5' is missing contents flag; assuming DATA.
POLINK: warning: Realigned section '.idata$5' in object 'libpnl.lib(0              1673985086  501   20    644     261       `
d†)' (from 4 to 8 byte(s)).
POLINK: warning: Section '.idata$4' is missing contents flag; assuming DATA.
POLINK: warning: Realigned section '.idata$4' in object 'libpnl.lib(0              1673985086  501   20    644     261       `
d†)' (from 4 to 8 byte(s)).
POLINK: warning: Section '.idata$6' is missing contents flag; assuming DATA.
POLINK: warning: Section '.idata$2' is missing contents flag; assuming DATA.
POLINK: warning: Realigned section '.idata$2' in object 'libpnl.lib(0              1673985086  501   20    644     261       `
d†)' (from 4 to 1 byte(s)).
POLINK: warning: Section '.idata$5' is missing contents flag; assuming DATA.
POLINK: warning: Realigned section '.idata$5' in object 'libpnl.lib(0              1673985086  501   20    644     261       `
d†)' (from 4 to 8 byte(s)).
POLINK: warning: Section '.idata$4' is missing contents flag; assuming DATA.
POLINK: warning: Realigned section '.idata$4' in object 'libpnl.lib(0              1673985086  501   20    644     261       `
d†)' (from 4 to 8 byte(s)).
POLINK: warning: Section '.idata$4' is missing contents flag; assuming DATA.
POLINK: warning: Realigned section '.idata$4' in object 'libpnl.lib(0              1673985086  501   20    644     261       `
d†)' (from 4 to 8 byte(s)).
POLINK: warning: Section '.idata$5' is missing contents flag; assuming DATA.
POLINK: warning: Realigned section '.idata$5' in object 'libpnl.lib(0              1673985086  501   20    644     261       `
d†)' (from 4 to 8 byte(s)).
POLINK: warning: Section '.idata$7' is missing contents flag; assuming DATA.

Can you give some advice how to debug this and to try to make pnl library to work with this compiler.

**Comment by milen-prg** [comment]
The problem was fixed in the Pelles C forums:
https://forum.pellesc.de/index.php?topic=10880.msg37656#msg37656

For the Pelles C compiler, the file libpnl.lib in the Release archive is with problem, so it generate with special command new such file from the libpnl.dll. And this works.

**Comment by jlelong** [comment]
@milen-prg Thanks for posting the solution here. FYI, the `libpnl.lib` file is only expected to work with the Visual Studio compiler.
